[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "magsim"
version = "0.1.1"
dependencies = ["numpy"]

[tool.setuptools]
include-package-data = true
packages = ["magsim"]
